### ISSUE TITLE
[DOC] cyclecloud import_cluster or import_template

### ISSUE THREAD

**Issue by AlexandreJean** [Azure/cyclecloud-lsf#11]
Hello

I am following the readme, and I am wondering in the section "Start an LSF cluster" if you want to run 
`cyclecloud import_cluster LSF -f lsf.txt -t`
 
or

`cyclecloud import_template LSF -f lsf.txt -t`

Thanks,
Alex

**Comment by mvrequa** [comment]
Thanks AJ - modified the readme to be more clear. Note: import_cluster has a sub command import_template which can be invoked by `-t`

https://github.com/Azure/cyclecloud-lsf/blame/master/README.md#L195
