### ISSUE TITLE
lsadmin reconfig call 6 times even if sucessfull

### ISSUE THREAD

**Issue by xpillons** [Azure/cyclecloud-lsf#16]
Why calling many time reconfig even if it succeed ? This is adding more time to startup.

https://github.com/Azure/cyclecloud-lsf/blob/master/specs/master/cluster-init/scripts/020_install_resource_connector.sh#L48-L52

**Comment by mvrequa** [comment]
Thanks XP - we've refactored the code. Will start lsf daemons in a simplified way.
