### ISSUE TITLE
jobs are not dispatched on execute nodes with v 3.2.0

### ISSUE THREAD

**Issue by amrragab8080** [Azure/cyclecloud-lsf#27]
Facility to stand up execute nodes works and nodes are added to the queue in lsf - but jobs do not get dispatched using the lsf-full.txt template. The problem is that the environment for the user is not pointing to the correct LSF_ENVDIR. An export needs to be set when restarting daemons on execute nodes:
https://github.com/Azure/cyclecloud-lsf/blob/32eeabc756793707ae26a803b1eb239050e811a4/specs/execute/cluster-init/files/user_data-full.sh#L64
needs to be:
`export LSF_ENVDIR=$LSF_ENVDIR_LOCAL`

Also incase a user logs into the compute node interactively the LSF_ENVDIR wont be set - needs an update to /etc/profile.d

**Comment by ryanhamel** [comment]
Closed out with PR 27
